### ISSUE TITLE
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [abacaj/mpt-30B-inference#3]
Hi,

When trying to run inference, I got the following error message:

```
Downloading (…)feaf43e4/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.24k/1.24k [00:00<00:00, 8.64MB/s]
Fetching 1 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.38it/s]
Traceback (most recent call last):
  File "/home/matthieu/Deployment/mpt-30B-inference/inference.py", line 49, in <module>
    llm = AutoModelForCausalLM.from_pretrained(
  File "/home/matthieu/anaconda3/envs/mpt_30b_cpu/lib/python3.10/site-packages/ctransformers/hub.py", line 157, in from_pretrained
    return LLM(
  File "/home/matthieu/anaconda3/envs/mpt_30b_cpu/lib/python3.10/site-packages/ctransformers/llm.py", line 206, in __init__
    self._lib = load_library(lib)
  File "/home/matthieu/anaconda3/envs/mpt_30b_cpu/lib/python3.10/site-packages/ctransformers/llm.py", line 102, in load_library
    lib = CDLL(path)
  File "/home/matthieu/anaconda3/envs/mpt_30b_cpu/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/matthieu/anaconda3/envs/mpt_30b_cpu/lib/python3.10/site-packages/ctransformers/lib/avx2/libctransformers.so)
```
I use an AMD® Ryzen threadripper 3960x 24-core processor × 48 on Ubuntu 18.04 LTS.

Thanks for any help!

**Comment by JovenChu** [comment]
@Matthieu-Tinycoaching Maybe you can try to install glibc for version 2.29 by this [blog](https://blog.csdn.net/m0_37201243/article/details/123641552)
