### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by j0schihatake** [abacaj/mpt-30B-inference#8]
Good afternoon, first of all, thank you for your work. It is very interesting. I am a java developer in production so I don't have much expertise in python. When I run the example from your youtube, I will give an error at the end.

Please tell me how much more difficult it would be to apply here rest communication by post request, if not difficult.

below is the description of the error:

(mpt30_final) D:\Develop\NeuronNetwork\Mpt30\mpt_30B_inference>python inference.py
Fetching 1 files: 100%|██████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Develop\NeuronNetwork\Mpt30\mpt_30B_inference\inference.py", line 49, in <module>
    llm = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\j0sch\miniconda3\envs\mpt30_final\lib\site-packages\ctransformers\hub.py", line 157, in from_pretrained
    return LLM(
  File "C:\Users\j0sch\miniconda3\envs\mpt30_final\lib\site-packages\ctransformers\llm.py", line 203, in __init__
    if not Path(model_path).is_file():
  File "C:\Users\j0sch\miniconda3\envs\mpt30_final\lib\pathlib.py", line 958, in __new__
    self = cls._from_parts(args)
  File "C:\Users\j0sch\miniconda3\envs\mpt30_final\lib\pathlib.py", line 592, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\j0sch\miniconda3\envs\mpt30_final\lib\pathlib.py", line 576, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by j0schihatake** [comment]
Found the reason, did not carefully look at your explanations. And thanks again for your work.
